# pandas: Arbeiten mit Tabellen
**Methoden der Data Science – Übung, WS 2026/27, Haya Halimeh**

Dieses Notebook baut auf der **Einführung in Python** auf. Dort haben Sie Variablen, Funktionen, Listen, Dictionaries und NumPy-Masken kennengelernt. Jetzt nutzen wir all das, um mit echten Tabellen zu arbeiten, und zwar wieder mit dem **BikeSharing-Datensatz**.

Wie gehabt ist das Ziel **nicht**, jede Zeile auswendig zu können, sondern **Code lesen und verstehen**, ihn **gezielt anpassen** und seinen **Output interpretieren** zu können.

Dafür gibt es immer wieder drei Arten von Zellen:
- 💡 **Konzept verstehen:** das Wichtigste eines Abschnitts in wenigen Sätzen.
- 🤔 **Erst denken, dann ausführen:** Überlegen Sie, was herauskommt, *bevor* Sie die Zelle starten.
- ✏️ **Ihr seid dran:** kleine Aufgaben zum Selbst-Schreiben.

Echte Daten liegen fast immer als **Tabelle** vor: Jede Zeile ist eine Beobachtung, jede Spalte eine Variable (im statistischen Sinn). Das Paket **pandas** stellt dafür den **DataFrame** bereit. Er ist das wichtigste Werkzeug in allen kommenden Notebooks.

## Daten laden und ansehen

In [1]:
import pandas as pd

data = pd.read_csv("https://raw.githubusercontent.com/kbrennig/MODS_WS25_26/refs/heads/main/data/BikeSharing.csv")
data

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5417,2011-12-19 19:00:00,4,0,1,2,14.76,17.425,53,11.0014,17,234,251
5418,2011-12-19 20:00:00,4,0,1,1,16.40,20.455,40,11.0014,9,197,206
5419,2011-12-19 21:00:00,4,0,1,2,14.76,17.425,53,8.9981,15,112,127
5420,2011-12-19 22:00:00,4,0,1,2,14.76,17.425,57,11.0014,12,95,107
5421,2011-12-19 23:00:00,4,0,1,1,14.76,17.425,53,11.0014,10,50,60

| Spalte | Bedeutung |
|---|---|
| `datetime` | Datum und Stunde |
| `season` | Jahreszeit (1 = Frühling, 2 = Sommer, 3 = Herbst, 4 = Winter) |
| `holiday`, `workingday` | Feiertag bzw. Arbeitstag (1 = ja, 0 = nein) |
| `weather` | Wetterkategorie (1 = klar … 4 = starker Regen) |
| `temp`, `atemp` | Temperatur bzw. gefühlte Temperatur in °C |
| `humidity`, `windspeed` | Luftfeuchtigkeit, Windgeschwindigkeit |
| `casual`, `registered`, `count` | Ausleihen ohne Abo, mit Abo, gesamt |

In [2]:
print(data.shape)   # (Anzahl Zeilen, Anzahl Spalten)

data.head(5)   # die ersten 5 Zeilen

(5422, 12)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

## Einen ersten Überblick bekommen
Bevor man rechnet, will man wissen, wie die Daten aussehen. **.describe()**  fasst alle Zahlenspalten zusammen: Anzahl, Mittelwert, Standardabweichung, Minimum, Quartile, Maximum.

In [3]:
data.describe()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
count,5422.000000,5422.000000,5422.000000,5422.000000,5422.000000,5422.000000,5422.000000,5422.000000,5422.000000,5422.000000,5422.000000
mean,2.511988,0.026558,0.682036,1.426411,19.751988,23.157086,63.405017,12.924144,28.737920,115.485430,144.223349
std,1.114603,0.160804,0.465728,0.647407,7.951694,8.619132,19.780518,8.354137,39.554419,108.847868,133.312123
min,1.000000,0.000000,0.000000,1.000000,2.460000,3.030000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,0.000000,1.000000,13.120000,15.910000,49.000000,7.001500,3.000000,27.000000,32.000000
50%,3.000000,0.000000,1.000000,1.000000,19.680000,23.485000,64.000000,12.998000,13.000000,91.000000,111.000000
75%,4.000000,0.000000,1.000000,2.000000,26.240000,31.060000,79.000000,19.001200,38.000000,168.000000,210.000000
max,4.000000,1.000000,1.000000,3.000000,38.540000,43.940000,100.000000,56.996900,272.000000,567.000000,638.000000

**.sort_values("spalte")** sortiert die Zeilen nach einer Spalte, standardmäßig aufsteigend. Mit dem benannten Argument ascending=False wird absteigend sortiert.

In [4]:
data.sort_values("count", ascending=False).head()   # die 5 Stunden mit den meisten Ausleihen

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
2587,2011-06-15 17:00:00,2,0,1,1,30.34,32.575,28,7.0015,83,555,638
3619,2011-09-01 17:00:00,3,0,1,1,29.52,33.335,54,16.9979,61,567,628
4480,2011-10-18 17:00:00,4,0,1,1,24.60,30.305,60,8.9981,72,553,625
4456,2011-10-17 17:00:00,4,0,1,1,22.96,26.515,64,8.9981,80,540,620
2011,2011-05-10 17:00:00,2,0,1,1,26.24,31.060,33,0.0000,79,532,611

## Spalten auswählen
Eine Spalte wählen wir aus wie einen Wert aus einem Dictionary, über ihren Namen. Heraus kommt eine **Series** (eine einzelne Spalte), die sich wie ein NumPy-Array verhält. Mehrere Spalten wählen wir mit einer **Liste** von Namen, also doppelten eckigen Klammern.

In [5]:
display(data["season"])   # wählen Sie eine Spalte aus, hier "season"
display(data[["temp", "humidity", "count"]].head()) # wählen Sie mehrere Spalten aus, hier "temp", "humidity" und "count"

0       1
1       1
2       1
3       1
4       1
       ..
5417    4
5418    4
5419    4
5420    4
5421    4
Name: season, Length: 5422, dtype: int64

   temp  humidity  count
0  9.84        81     16
1  9.02        80     40
2  9.02        80     32
3  9.84        75     13
4  9.84        75      1

**.value_counts()** zählt, wie oft jeder Wert in einer Spalte vorkommt.

In [6]:
data["weather"].value_counts()    # wie viele Stunden pro Wetterkategorie?

weather
1    3583
2    1366
3     473
Name: count, dtype: int64

## Zeilen filtern
Hier kommen die Masken aus dem Python-Intro (Teil 5) zurück: Eine Bedingung auf eine Spalte ergibt eine Maske, und mit der Maske wählen wir Zeilen aus.

In [7]:
display(data.iloc[0])   # erste Zeile

datetime      2011-01-01 00:00:00
season                          1
holiday                         0
workingday                      0
weather                         1
temp                         9.84
atemp                      14.395
humidity                       81
windspeed                     0.0
casual                          3
registered                     13
count                          16
Name: 0, dtype: object

In [8]:

maske_warm = data["temp"] > 30 # eine Maske, die True für alle Zeilen mit Temperatur > 30 zurückgibt
display(data[maske_warm].head()) # die ersten 5 Zeilen mit Temperatur > 30 °C

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
1409,2011-04-04 14:00:00,2,0,1,2,30.34,32.575,27,32.9975,47,76,123
1410,2011-04-04 15:00:00,2,0,1,1,31.16,33.335,23,36.9974,47,96,143
1411,2011-04-04 16:00:00,2,0,1,1,31.16,32.575,22,35.0008,59,130,189
1412,2011-04-04 17:00:00,2,0,1,1,30.34,32.575,23,40.9973,83,283,366
1577,2011-04-11 15:00:00,2,0,1,1,30.34,33.335,48,35.0008,56,85,141

Mehrere Bedingungen werden mit `&` (und) bzw. `|` (oder) verknüpft. Jede Bedingung muss dabei in **eigenen Klammern** stehen.

In [9]:
warm_und_arbeitstag = data[(data["temp"] > 30) & (data["workingday"] == 1)]
print(len(warm_und_arbeitstag), "Stunden mit über 30 °C an Arbeitstagen")

439 Stunden mit über 30 °C an Arbeitstagen

## Neue Spalten berechnen
Rechnen mit Spalten ist **vektorisiert**, wirkt also auf alle Zeilen auf einmal.

In [10]:
data["anteil_casual"] = data["casual"] / data["count"]
data[["casual", "count", "anteil_casual"]].head()

   casual  count  anteil_casual
0       3     16       0.187500
1       8     40       0.200000
2       5     32       0.156250
3       3     13       0.230769
4       0      1       0.000000

## Subset aus einem DataFrame

Die Auswahl alässt sich wie jeder andere Wert in einer **neuen Variable** speichern. `subset` ist dann eine eigene, kleinere Tabelle mit nur diesen drei Spalten, und `data` bleibt unverändert.

In [11]:
subset = data[["temp", "humidity", "count"]]
subset

       temp  humidity  count
0      9.84        81     16
1      9.02        80     40
2      9.02        80     32
3      9.84        75     13
4      9.84        75      1
...     ...       ...    ...
5417  14.76        53    251
5418  16.40        40    206
5419  14.76        53    127
5420  14.76        57    107
5421  14.76        53     60

[5422 rows x 3 columns]

## Eine Funktion auf jeden Wert anwenden
Mit `.apply(funktion)` wendet pandas eine Funktion auf **jeden einzelnen Wert** einer Spalte an. Das Ergebnis ist eine neue Spalte mit genauso vielen Zeilen.

Beispiel: Wir teilen die Temperatur in drei Kategorien ein. Dafür schreiben wir eine Funktion, die **einen** Wert bekommt und **eine** Kategorie zurückgibt. pandas ruft sie dann für jede der 5422 Zeilen auf. Wir zeigen die ersten 20 Zeilen aus dem DataFrame.

In [12]:
def temperatur_kategorie(t):
    if t < 10:
        return "kalt"
    elif t < 25:
        return "mild"
    else:
        return "warm"

data["temp_kategorie"] = data["temp"].apply(temperatur_kategorie)   
data[["temp", "temp_kategorie"]].head(20)

     temp temp_kategorie
0    9.84           kalt
1    9.02           kalt
2    9.02           kalt
3    9.84           kalt
4    9.84           kalt
5    9.84           kalt
6    9.02           kalt
7    8.20           kalt
8    9.84           kalt
9   13.12           mild
10  15.58           mild
11  14.76           mild
12  17.22           mild
13  18.86           mild
14  18.86           mild
15  18.04           mild
16  17.22           mild
17  18.04           mild
18  17.22           mild
19  17.22           mild

✏️ **Ihr seid dran:**
1. Schreiben Sie eine Funktion `ist_wochenende(workingday)`, die `"frei"` zurückgibt, wenn `workingday` 0 ist, und sonst `"Arbeitstag"`.
2. Wenden Sie die Funktion mit `.apply` auf die Spalte `workingday` an und speichern Sie das Ergebnis als neue Spalte `tagtyp`. Zeigen Sie die ersten 50 Zeilen von `workingday` und `tagtyp` an.

In [ ]:
# 1.

# 2.

# Daten transformieren und bereinigen

In der Vorlesung *Transformation and Cleaning* ging es um Normalisierung, Joins, Unions und typische Datenprobleme. Hier sehen Sie, wie das in pandas aussieht.

## Spalten und Zeilen entfernen
Mit `.drop(columns=[...])` entfernen wir Spalten. Wie viele pandas-Methoden gibt `.drop` eine **neue** Tabelle zurück. `data` selbst bleibt unverändert, solange wir das Ergebnis nicht wieder in `data` speichern.

In [13]:
data_klein = data.drop(columns=["atemp", "casual", "registered"])

print(data.shape)        # Original
print(data_klein.shape)  # drei Spalten weniger

(5422, 14)
(5422, 11)

Zeilen entfernen heißt in pandas fast immer **filtern**: Wir behalten nur die Zeilen, die eine Bedingung erfüllen.

In [14]:
arbeitstage = data[data["workingday"] != 0]   # alle Stunden ohne Regen behalten
print("vor der Filterung:", len(data), "-> Nach der Filterung:", len(arbeitstage), "Zeilen")

vor der Filterung: 5422 -> Nach der Filterung: 3698 Zeilen

🤔 **Erst denken, dann ausführen:** Hat `data` nach der folgenden Zelle noch die Spalte `atemp`?

In [ ]:
data.drop(columns=["atemp"])
print("atemp" in data.columns)

## Fehlende Werte und Duplikate
Vor jeder Analyse sollte man prüfen, ob die Daten „sauber“ sind. Zwei typische Probleme:

- **Fehlende Werte:** leere Zellen, in pandas als `NaN` („Not a Number“) angezeigt
- **Duplikate:** Zeilen, die komplett doppelt vorkommen, z. B. weil Daten zweimal importiert wurden

`.isna()` erzeugt eine Maske: `True` überall dort, wo ein Wert fehlt. `.duplicated()` markiert jede Zeile, die schon einmal vorkam. Mit `.sum()` zählen wir die Treffer.

Damit Sie sehen, wie es aussieht, wenn nicht, bauen wir eine kleine Tabelle von Hand. Ein DataFrame lässt sich direkt aus einem **Dictionary aus Listen** erzeugen: ein Schlüssel pro Spalte.

In [15]:
import numpy as np

messungen = pd.DataFrame({
    "station":   ["A",      "A",      "B",      "B",      "B"],
    "datum":     ["01.05.", "02.05.", "01.05.", "02.05.", "02.05."],
    "ausleihen": [120,      np.nan,   80,       95,       95],
})
messungen

  station   datum  ausleihen
0       A  01.05.      120.0
1       A  02.05.        NaN
2       B  01.05.       80.0
3       B  02.05.       95.0
4       B  02.05.       95.0

In [16]:
print(messungen.isna().sum())        # fehlende Werte pro Spalte
print(messungen.duplicated().sum())  # komplett doppelte Zeilen

station      0
datum        0
ausleihen    1
dtype: int64
1

In [ ]:
bereinigt = messungen.drop_duplicates() #  Duplikate entfernen
bereinigt = messungen.dropna()   # Zeilen mit fehlenden Werten entfernen
bereinigt


## Union: Tabellen untereinander hängen
Bei einer **Union** werden Tabellen mit denselben Spalten **untereinander** gehängt, z. B. zwei Exporte aus demselben System. In pandas geht das mit `pd.concat([...])`. `ignore_index=True` nummeriert die Zeilen danach neu durch.

In [17]:
export_montag = pd.DataFrame({"part_id": [367, 856], "batch": ["006", "009"], "quantity": [200, 550]})
export_dienstag = pd.DataFrame({"part_id": [856, 562], "batch": ["009", "002"], "quantity": [550, 830]})

alle_batches = pd.concat([export_montag, export_dienstag], ignore_index=True)
alle_batches

   part_id batch  quantity
0      367   006       200
1      856   009       550
2      856   009       550
3      562   002       830

## Join: Tabellen über einen Schlüssel verbinden
Ein **Join** verbindet Tabellen wieder über einen gemeinsamen Schlüssel. In pandas: `pd.merge()`.

Hier zwei Tabellen aus der Normalisierungsaufgabe. In der Werk-Tabelle fehlt absichtlich Münster:

In [19]:
teile = pd.DataFrame({
    "part_id":      [367, 856, 562],
    "denomination": ["Lever", "Hand-wheel", "Screw"],
    "color":        ["silver", "black", "grey"],
    "zip_code":     ["33095", "33613", "48143"],
})
werke = pd.DataFrame({
    "zip_code": ["33095", "33613"],
    "facility": ["Paderborn", "Bielefeld"],
})
display(teile)
display(werke)

   part_id denomination   color zip_code
0      367        Lever  silver    33095
1      856   Hand-wheel   black    33613
2      562        Screw    grey    48143

  zip_code   facility
0    33095  Paderborn
1    33613  Bielefeld

In [20]:
pd.merge(teile, werke, on="zip_code", how="inner")   # nur Zeilen, deren Schlüssel in BEIDEN Tabellen vorkommt

   part_id denomination   color zip_code   facility
0      367        Lever  silver    33095  Paderborn
1      856   Hand-wheel   black    33613  Bielefeld

In [21]:
pd.merge(teile, werke, on="zip_code", how="outer")    # alle Zeilen aus der linken Tabelle

   part_id denomination   color zip_code   facility
0      367        Lever  silver    33095  Paderborn
1      856   Hand-wheel   black    33613  Bielefeld
2      562        Screw    grey    48143        NaN

> 💡 **Konzept – Welcher Join?**
>
> | `how=` | Ergebnis |
> |---|---|
> | `"inner"` | nur Zeilen mit passendem Schlüssel in **beiden** Tabellen – die Schraube (48143) verschwindet |
> | `"outer"` | alle Zeilen aus beiden Tabellen |
>



✏️ **Ihr seid dran:**
Gegeben ist eine Tabelle `wetter_namen` mit den Spalten `weather` (Werte 1, 2, 3, 4) und `wetter_text` (`"klar"`, `"bewölkt"`, `"leichter Regen"`, `"starker Regen"`).
1. Verbinden Sie `data` per Join (`how="outer"`) über die Spalte `weather` mit `wetter_namen` und speichern Sie das Ergebnis als `data_wetter`. 
2. Zeigen Sie die ersten 5 Zeilen der Spalten `weather` und `wetter_text` an.

In [ ]:
#gegeben 
wetter_namen = pd.DataFrame({"weather": [1, 2, 3, 4],
                             "wetter_text": ["klar", "bewölkt", "leichter Regen", "starker Regen"]})

display(wetter_namen)


# 1.

# 2.

# Was Sie jetzt können

Einen Datensatz laden und erkunden, Spalten auswählen, Zeilen filtern, neue Spalten berechnen und eigene Funktionen mit `.apply` anwenden.

Spalten und Zeilen entfernen, fehlende Werte und Duplikate finden und bereinigen sowie Tabellen per Union (`pd.concat`) und Join (`pd.merge`) zusammenführen – und erklären, warum dabei Datenprobleme entstehen können.